async function main(): Promise<void> {}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
